-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: DEV - GOLD - Sprint 03 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_GOLD.MV_HIGH_VALUE_CUSTOMERS
CREATE OR REPLACE MATERIALIZED VIEW "SQLDBM_DEMO".HEATHER_GOLD.MV_HIGH_VALUE_CUSTOMERS
(
  CUSTOMER_HASH_KEY,
  CUSTKEY,
  NAME,
  MKTSEGMENT,
  ACCTBAL,
  CUSTOMER_TIER
)
COMMENT = 'Materialized view: pre-filtered projection of DIM_CUSTOMER limited to CUSTOMER_TIER = HIGH_VALUE. Single base table, no joins -- Snowflake materialized views do not support joins, so this stays deliberately within that constraint rather than attempting a cross-table rollup.'
AS
SELECT
    CUSTOMER_HASH_KEY,
    CUSTKEY,
    NAME,
    MKTSEGMENT,
    ACCTBAL,
    CUSTOMER_TIER
FROM "SQLDBM_DEMO".HEATHER_GOLD.DIM_CUSTOMER
WHERE CUSTOMER_TIER = 'HIGH_VALUE';

