-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_VENDOR_EDI.STG_EDI_SUPPLIER
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_VENDOR_EDI.STG_EDI_SUPPLIER
(
 STAGE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of this table''s own business key: VEND_CD',
 VEND_CD        varchar(20) NOT NULL COMMENT 'Vendor code (business key) -- different flavor than ERP SUPPLIERKEY',
 VEND_NM        varchar(100) COMMENT 'Vendor name',
 VEND_ADDR      varchar(150) COMMENT 'Vendor address, single unparsed field',
 VEND_PHN       varchar(20) COMMENT 'Vendor phone number',
 VEND_BAL_AMT   varchar(20) COMMENT 'Vendor account balance, landed as text per raw EDI convention',
 BATCH_ID       varchar(30) COMMENT 'Referenced batch business key -- virtual relationship only',
 SOURCE_SYSTEM  varchar(50) NOT NULL DEFAULT 'VENDOR_EDI' COMMENT 'Source system code',
 LOAD_TIMESTAMP timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_EDI_SUPPLIER PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for vendor supplier data from the EDI feed. Append-only.';
