-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_STORE_POS
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_STORE_POS
(
 STORE_HASH_KEY   varchar(64) NOT NULL COMMENT 'FK to HUB_STORE',
 LOAD_DATE        timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF        varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 STORE_NAME       varchar(100) COMMENT 'Store display name',
 STORE_REGION_TXT varchar(50) COMMENT 'Free-text region name as captured at POS, not conformed to HUB_REGION',
 OPEN_DATE_TXT    varchar(20) COMMENT 'Store open date, landed as text',
 RECORD_SOURCE    varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_STORE_POS PRIMARY KEY ( STORE_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_STORE_POS_HUB_STORE FOREIGN KEY ( STORE_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_STORE ( STORE_HASH_KEY )
)
COMMENT = 'Satellite: descriptive attributes of a retail store, from POS. Insert-only, new row only when HASH_DIFF changes.';
