-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_PARTSUPP
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_PARTSUPP
(
 LNK_PARTSUPP_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of the VEND_CD + VEND_PART_CD combination',
 PRODUCT_HASH_KEY      varchar(64) NOT NULL COMMENT 'FK to HUB_PRODUCT',
 SUPPLIER_HASH_KEY     varchar(64) NOT NULL COMMENT 'FK to HUB_SUPPLIER',
 RECORD_SOURCE         varchar(50) NOT NULL COMMENT 'Source system that asserted this relationship',
 LOAD_DATE             timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this relationship was first loaded',

 CONSTRAINT pk_LNK_PARTSUPP PRIMARY KEY ( LNK_PARTSUPP_HASH_KEY ),
 CONSTRAINT fk_LNK_PARTSUPP_HUB_PRODUCT FOREIGN KEY ( PRODUCT_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_PRODUCT ( PRODUCT_HASH_KEY ),
 CONSTRAINT fk_LNK_PARTSUPP_HUB_SUPPLIER FOREIGN KEY ( SUPPLIER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SUPPLIER ( SUPPLIER_HASH_KEY )
)
COMMENT = 'Link: a vendor EDI supply relationship ties a product to a supplier. Insert-only.';
