-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_SALE_LINE
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_SALE_LINE
(
 LNK_SALE_LINE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of the SALE_TICKET_NO + SKU + LINE_SEQ combination',
 SALE_HASH_KEY          varchar(64) NOT NULL COMMENT 'FK to HUB_SALE',
 PRODUCT_HASH_KEY       varchar(64) NOT NULL COMMENT 'FK to HUB_PRODUCT',
 LINE_SEQ               number(38,0) NOT NULL COMMENT 'Degenerate key element -- distinguishes multiple lines within the same sale/product combination',
 RECORD_SOURCE          varchar(50) NOT NULL COMMENT 'Source system that asserted this relationship',
 LOAD_DATE              timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this relationship was first loaded',

 CONSTRAINT pk_LNK_SALE_LINE PRIMARY KEY ( LNK_SALE_LINE_HASH_KEY ),
 CONSTRAINT fk_LNK_SALE_LINE_HUB_PRODUCT FOREIGN KEY ( PRODUCT_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_PRODUCT ( PRODUCT_HASH_KEY ),
 CONSTRAINT fk_LNK_SALE_LINE_HUB_SALE FOREIGN KEY ( SALE_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SALE ( SALE_HASH_KEY )
)
COMMENT = 'Link: a retail sale line ties a sale to a product. Insert-only.';
