-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_LOYALTY_CUSTOMER
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_LOYALTY_CUSTOMER
(
 LOYALTY_CUSTOMER_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of LOYALTY_ID. Sourced directly from POS Stage STAGE_HASH_KEY.',
 LOYALTY_ID                varchar(20) NOT NULL COMMENT 'Business key: POS loyalty program identifier',
 RECORD_SOURCE             varchar(50) NOT NULL COMMENT 'Source system that first introduced this business key',
 LOAD_DATE                 timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this business key was first loaded',

 CONSTRAINT pk_HUB_LOYALTY_CUSTOMER PRIMARY KEY ( LOYALTY_CUSTOMER_HASH_KEY )
)
COMMENT = 'Hub: retail/POS loyalty customer business entity. Deliberately separate from HUB_CUSTOMER -- distinct population, not a same-as candidate. Insert-only.';
