-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_VENDOR_EDI.STG_EDI_BATCH_HEADER
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_VENDOR_EDI.STG_EDI_BATCH_HEADER
(
 STAGE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of this table''s own business key: BATCH_ID',
 BATCH_ID       varchar(30) NOT NULL COMMENT 'EDI batch identifier for this file drop (business key)',
 FILE_NM        varchar(200) COMMENT 'Name of the source EDI file',
 VEND_CD        varchar(20) COMMENT 'Referenced vendor business key -- virtual relationship only',
 RECEIVED_DTTM  timestamp_ltz(9) COMMENT 'Timestamp the batch file was received',
 RECORD_CNT     number(38,0) COMMENT 'Number of records in the batch, per file trailer',
 PROCESS_STATUS varchar(20) COMMENT 'Batch processing status (RECEIVED, LOADED, ERROR)',
 SOURCE_SYSTEM  varchar(50) NOT NULL DEFAULT 'VENDOR_EDI' COMMENT 'Source system code',
 LOAD_TIMESTAMP timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_EDI_BATCH_HEADER PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for EDI batch/file metadata -- captures file-based ingestion lineage. Append-only.';
