-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_BUSINESS.SAL_PRODUCT
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_BUSINESS.SAL_PRODUCT
(
 SAL_PRODUCT_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of the two participating PRODUCT_HASH_KEY values (normalized ordering to avoid duplicate reversed pairs)',
 PRODUCT_HASH_KEY_1   varchar(64) NOT NULL COMMENT 'FK to HEATHER_SILVER_RAW.HUB_PRODUCT -- one side of the match',
 PRODUCT_HASH_KEY_2   varchar(64) NOT NULL COMMENT 'FK to HEATHER_SILVER_RAW.HUB_PRODUCT -- the other side of the match',
 RECORD_SOURCE        varchar(50) NOT NULL COMMENT 'Not a source system -- this is a derived judgment. Convention: DBT_DERIVED',
 LOAD_DATE            timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this match was first asserted',

 CONSTRAINT pk_SAL_PRODUCT PRIMARY KEY ( SAL_PRODUCT_HASH_KEY ),
 CONSTRAINT fk_SAL_PRODUCT_HUB_PRODUCT_1 FOREIGN KEY ( PRODUCT_HASH_KEY_1 ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_PRODUCT ( PRODUCT_HASH_KEY ),
 CONSTRAINT fk_SAL_PRODUCT_HUB_PRODUCT_2 FOREIGN KEY ( PRODUCT_HASH_KEY_2 ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_PRODUCT ( PRODUCT_HASH_KEY )
)
COMMENT = 'Same-as-link: asserts that two HUB_PRODUCT rows (typically from different sources) represent the same real-world product. Insert-only.';
