-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_SUPPLIER_EDI
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_SUPPLIER_EDI
(
 SUPPLIER_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to HUB_SUPPLIER',
 LOAD_DATE         timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF         varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 VEND_NM           varchar(100) COMMENT 'Vendor name',
 VEND_ADDR         varchar(150) COMMENT 'Vendor address, single unparsed field',
 VEND_PHN          varchar(20) COMMENT 'Vendor phone number',
 VEND_BAL_AMT      varchar(20) COMMENT 'Vendor account balance, landed as text per raw EDI convention -- cast/cleansed in Silver Business',
 RECORD_SOURCE     varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_SUPPLIER_EDI PRIMARY KEY ( SUPPLIER_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_SUPPLIER_EDI_HUB_SUPPLIER FOREIGN KEY ( SUPPLIER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SUPPLIER ( SUPPLIER_HASH_KEY )
)
COMMENT = 'Satellite: descriptive attributes of a supplier, from the vendor EDI feed. Insert-only, new row only when HASH_DIFF changes.';
