-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_ORDER_ERP
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_ORDER_ERP
(
 LNK_ORDER_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to LNK_ORDER',
 LOAD_DATE          timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF          varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 ORDERSTATUS        varchar(1) COMMENT 'Status of the order (O/F/P)',
 TOTALPRICE         number(12,2) COMMENT 'Total price of the order',
 ORDERDATE          date COMMENT 'Date when the order was placed',
 ORDERPRIORITY      varchar(15) COMMENT 'Priority of the order',
 CLERK              varchar(15) COMMENT 'Clerk responsible for the order',
 SHIPPRIORITY       number(38,0) COMMENT 'Shipping priority of the order',
 COMMENT            varchar(79) COMMENT 'Additional comments about the order',
 RECORD_SOURCE      varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_ORDER_ERP PRIMARY KEY ( LNK_ORDER_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_ORDER_ERP_LNK_ORDER FOREIGN KEY ( LNK_ORDER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_ORDER ( LNK_ORDER_HASH_KEY )
)
COMMENT = 'Satellite: transactional attributes of the order-customer relationship, from ERP. Insert-only, new row only when HASH_DIFF changes (e.g. order status progresses).';
