-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_PRODUCT_ERP
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_PRODUCT_ERP
(
 PRODUCT_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to HUB_PRODUCT',
 LOAD_DATE        timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF        varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 NAME             varchar(55) COMMENT 'Name of the part',
 MFGR             varchar(25) COMMENT 'Manufacturer of the part',
 BRAND            varchar(10) COMMENT 'Brand of the part',
 TYPE             varchar(25) COMMENT 'Type or category of the part',
 SIZE             number(38,0) COMMENT 'Size of the part',
 CONTAINER        varchar(10) COMMENT 'Container type used for the part',
 RETAILPRICE      number(12,2) COMMENT 'Retail price of the part',
 COMMENT          varchar(23) COMMENT 'Additional comments about the part',
 RECORD_SOURCE    varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_PRODUCT_ERP PRIMARY KEY ( PRODUCT_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_PRODUCT_ERP_HUB_PRODUCT FOREIGN KEY ( PRODUCT_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_PRODUCT ( PRODUCT_HASH_KEY )
)
COMMENT = 'Satellite: descriptive attributes of a product, from ERP. Insert-only, new row only when HASH_DIFF changes.';
