-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_SUPPLIER_ERP
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_SUPPLIER_ERP
(
 SUPPLIER_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to HUB_SUPPLIER',
 LOAD_DATE         timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF         varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 SUPPLIERNAME      varchar(25) COMMENT 'Name of the supplier',
 ADDRESS           varchar(40) COMMENT 'Address of the supplier',
 PHONE             varchar(15) COMMENT 'Contact phone number of the supplier',
 ACCOUNTBALANCE    number(12,2) COMMENT 'Account balance of the supplier',
 COMMENT           varchar(303) COMMENT 'Additional comments about the supplier',
 RECORD_SOURCE     varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_SUPPLIER_ERP PRIMARY KEY ( SUPPLIER_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_SUPPLIER_ERP_HUB_SUPPLIER FOREIGN KEY ( SUPPLIER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SUPPLIER ( SUPPLIER_HASH_KEY )
)
COMMENT = 'Satellite: descriptive attributes of a supplier, from ERP. Insert-only, new row only when HASH_DIFF changes.';
