-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_VENDOR_EDI.STG_EDI_PART
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_VENDOR_EDI.STG_EDI_PART
(
 STAGE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of this table''s own business key: VEND_PART_CD',
 VEND_PART_CD   varchar(30) NOT NULL COMMENT 'Vendor''s own part code (business key) -- different flavor than ERP PARTKEY',
 VEND_PART_DESC varchar(200) COMMENT 'Vendor''s part description text',
 VEND_CD        varchar(20) COMMENT 'Referenced vendor business key -- virtual relationship only',
 UNIT_CST_AMT   varchar(20) COMMENT 'Unit cost, landed as text per raw EDI convention',
 PKG_CD         varchar(10) COMMENT 'Vendor packaging code',
 BATCH_ID       varchar(30) COMMENT 'Referenced batch business key -- virtual relationship only',
 SOURCE_SYSTEM  varchar(50) NOT NULL DEFAULT 'VENDOR_EDI' COMMENT 'Source system code',
 LOAD_TIMESTAMP timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_EDI_PART PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for vendor part catalog data from the EDI feed. Append-only.';
