-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_POS.STG_POS_SALE
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_POS.STG_POS_SALE
(
 STAGE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of this table''s own business key: SALE_TICKET_NO',
 SALE_TICKET_NO varchar(30) NOT NULL COMMENT 'POS sale ticket number (business key) -- different flavor than ERP ORDERKEY',
 LOYALTY_ID     varchar(20) COMMENT 'Referenced loyalty customer business key -- virtual relationship only, nullable for non-loyalty sales',
 STORE_ID       varchar(20) COMMENT 'Referenced store business key -- virtual relationship only',
 SALE_DATE_TXT  varchar(20) COMMENT 'Sale date landed as text',
 SALE_STATUS    varchar(20) COMMENT 'POS sale status -- different domain values than ERP ORDERSTATUS (e.g. COMPLETED, VOIDED, RETURNED)',
 CASHIER_NAME   varchar(100) COMMENT 'Name of the cashier who processed the sale',
 FILE_LOAD_DATE varchar(20) COMMENT 'Source-asserted file date, landed as text',
 SOURCE_SYSTEM  varchar(50) NOT NULL DEFAULT 'POS' COMMENT 'Source system code',
 LOAD_TIMESTAMP timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_POS_SALE PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for POS sale (transaction header) data. Append-only.';
