-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_BUSINESS.SAL_SUPPLIER
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_BUSINESS.SAL_SUPPLIER
(
 SAL_SUPPLIER_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of the two participating SUPPLIER_HASH_KEY values (normalized ordering to avoid duplicate reversed pairs)',
 SUPPLIER_HASH_KEY_1   varchar(64) NOT NULL COMMENT 'FK to HEATHER_SILVER_RAW.HUB_SUPPLIER -- one side of the match',
 SUPPLIER_HASH_KEY_2   varchar(64) NOT NULL COMMENT 'FK to HEATHER_SILVER_RAW.HUB_SUPPLIER -- the other side of the match',
 RECORD_SOURCE         varchar(50) NOT NULL COMMENT 'Not a source system -- this is a derived judgment. Convention: DBT_DERIVED',
 LOAD_DATE             timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this match was first asserted',

 CONSTRAINT pk_SAL_SUPPLIER PRIMARY KEY ( SAL_SUPPLIER_HASH_KEY ),
 CONSTRAINT fk_SAL_SUPPLIER_HUB_SUPPLIER_1 FOREIGN KEY ( SUPPLIER_HASH_KEY_1 ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SUPPLIER ( SUPPLIER_HASH_KEY ),
 CONSTRAINT fk_SAL_SUPPLIER_HUB_SUPPLIER_2 FOREIGN KEY ( SUPPLIER_HASH_KEY_2 ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SUPPLIER ( SUPPLIER_HASH_KEY )
)
COMMENT = 'Same-as-link: asserts that two HUB_SUPPLIER rows (ERP and EDI) represent the same real-world supplier. Insert-only.';
