-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: DEV - GOLD - Sprint 03 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_GOLD.FACT_ORDER
CREATE TABLE "SQLDBM_DEMO".HEATHER_GOLD.FACT_ORDER
(
 LNK_ORDER_HASH_KEY varchar(64) NOT NULL COMMENT 'Reused from HEATHER_SILVER_RAW.LNK_ORDER -- same key, joinable straight back to Silver',
 CUSTOMER_HASH_KEY  varchar(64) NOT NULL COMMENT 'FK to DIM_CUSTOMER',
 ORDERKEY           number(38,0) COMMENT 'Degenerate business key, retained for filtering/readability',
 ORDERSTATUS        varchar(1) COMMENT 'Status of the order (O/F/P)',
 TOTALPRICE         number(12,2) COMMENT 'Total price of the order',
 ORDERDATE          date COMMENT 'Date when the order was placed',
 ORDERPRIORITY      varchar(15) COMMENT 'Priority of the order',

 CONSTRAINT pk_FACT_ORDER PRIMARY KEY ( LNK_ORDER_HASH_KEY ),
 CONSTRAINT fk_FACT_ORDER_DIM_CUSTOMER FOREIGN KEY ( CUSTOMER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_GOLD.DIM_CUSTOMER ( CUSTOMER_HASH_KEY )
)
COMMENT = 'Gold fact: consumption-ready wholesale order, built from LNK_ORDER + SAT_ORDER_ERP (current). Refreshed as a full snapshot on each dbt run.';
