-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_CUSTOMER
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_CUSTOMER
(
 STAGE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of this table''s own business key: CUSTKEY',
 CUSTKEY        number(38,0) NOT NULL COMMENT 'ERP customer master key (business key)',
 NAME           varchar(25) COMMENT 'Name of the customer',
 ADDRESS        varchar(40) COMMENT 'Address of the customer',
 NATIONKEY      number(38,0) COMMENT 'Referenced nation business key -- virtual relationship only',
 PHONE          varchar(15) COMMENT 'Contact phone number of the customer',
 ACCTBAL        number(12,2) COMMENT 'Account balance of the customer',
 MKTSEGMENT     varchar(10) COMMENT 'Market segment classification of the customer',
 COMMENT        varchar(117) COMMENT 'Additional comments about the customer',
 SOURCE_SYSTEM  varchar(50) NOT NULL DEFAULT 'ERP' COMMENT 'Source system code',
 LOAD_TIMESTAMP timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_ERP_CUSTOMER PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for ERP customer master data (wholesale). Append-only.';
