-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_ORDER_LINES
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_ORDER_LINES
(
 STAGE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of this table''s own composite business key: ORDERKEY + LINENUMBER',
 ORDERKEY       number(38,0) NOT NULL COMMENT 'Referenced order business key -- virtual relationship only',
 PARTKEY        number(38,0) NOT NULL COMMENT 'Referenced part business key -- virtual relationship only',
 SUPPKEY        number(38,0) NOT NULL COMMENT 'Referenced supplier business key -- virtual relationship only',
 LINENUMBER     number(38,0) NOT NULL COMMENT 'Line item number within an order (part of this table''s own business key)',
 QUANTITY       number(12,2) COMMENT 'Quantity of the item ordered',
 EXTENDEDPRICE  number(12,2) COMMENT 'Extended price of the item (quantity * unit price)',
 DISCOUNT       number(12,4) COMMENT 'Discount rate applied to the item, as a decimal fraction',
 TAX            number(12,4) COMMENT 'Tax rate applied to the item, as a decimal fraction',
 RETURNFLAG     varchar(1) COMMENT 'Return status of the item',
 LINESTATUS     varchar(1) COMMENT 'Status of the line item',
 SHIPDATE       date COMMENT 'Date the item was shipped',
 COMMITDATE     date COMMENT 'Date the item was committed for shipping',
 RECEIPTDATE    date COMMENT 'Date the item was received',
 SHIPINSTRUCT   varchar(25) COMMENT 'Shipping instructions for the item',
 SHIPMODE       varchar(10) COMMENT 'Shipping mode for the item',
 COMMENT        varchar(44) COMMENT 'Additional comments about the line item',
 SOURCE_SYSTEM  varchar(50) NOT NULL DEFAULT 'ERP' COMMENT 'Source system code',
 LOAD_TIMESTAMP timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_ERP_ORDER_LINES PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for ERP wholesale order line items. Append-only.';
