-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_SALE
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_SALE
(
 LNK_SALE_HASH_KEY         varchar(64) NOT NULL COMMENT 'Hash of the SALE_TICKET_NO + LOYALTY_ID + STORE_ID combination',
 SALE_HASH_KEY             varchar(64) NOT NULL COMMENT 'FK to HUB_SALE',
 LOYALTY_CUSTOMER_HASH_KEY varchar(64) COMMENT 'FK to HUB_LOYALTY_CUSTOMER; nullable -- not every sale is tied to a loyalty account',
 STORE_HASH_KEY            varchar(64) NOT NULL COMMENT 'FK to HUB_STORE',
 RECORD_SOURCE             varchar(50) NOT NULL COMMENT 'Source system that asserted this relationship',
 LOAD_DATE                 timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this relationship was first loaded',

 CONSTRAINT pk_LNK_SALE PRIMARY KEY ( LNK_SALE_HASH_KEY ),
 CONSTRAINT fk_LNK_SALE_HUB_LOYALTY_CUSTOMER FOREIGN KEY ( LOYALTY_CUSTOMER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_LOYALTY_CUSTOMER ( LOYALTY_CUSTOMER_HASH_KEY ),
 CONSTRAINT fk_LNK_SALE_HUB_SALE FOREIGN KEY ( SALE_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SALE ( SALE_HASH_KEY ),
 CONSTRAINT fk_LNK_SALE_HUB_STORE FOREIGN KEY ( STORE_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_STORE ( STORE_HASH_KEY )
)
COMMENT = 'Link: a retail sale ties a sale ticket to a loyalty customer (optional) and a store. Insert-only.';
