-- **************************** SqlDBM: Snowflake ****************************
-- * Generated by SqlDBM: DEV - GOLD - Sprint 03 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_GOLD.DIM_CUSTOMER
CREATE OR REPLACE TABLE "SQLDBM_DEMO".HEATHER_GOLD.DIM_CUSTOMER
(
 CUSTOMER_HASH_KEY varchar(64) NOT NULL COMMENT 'Reused from HEATHER_SILVER_RAW.HUB_CUSTOMER -- same key, joinable straight back to Silver',
 CUSTKEY           number(38,0) COMMENT 'Degenerate business key, retained for filtering/readability',
 NAME              varchar(25) COMMENT 'Name of the customer',
 ADDRESS           varchar(40) COMMENT 'Address of the customer',
 PHONE             varchar(15) COMMENT 'Contact phone number of the customer',
 ACCTBAL           number(12,2) COMMENT 'Account balance of the customer',
 MKTSEGMENT        varchar(10) COMMENT 'Market segment classification of the customer',
 CUSTOMER_TIER     varchar(20) COMMENT 'Derived business classification, from HEATHER_SILVER_BUSINESS.SAT_CUSTOMER_BUSINESS',
 RECORD_SOURCE     varchar(50) COMMENT 'Source system for the base attributes (business rule fields are DBT_DERIVED upstream)',

 CONSTRAINT pk_DIM_CUSTOMER PRIMARY KEY ( CUSTOMER_HASH_KEY )
)
COMMENT = 'Gold dimension: consumption-ready wholesale customer, built from HUB_CUSTOMER + SAT_CUSTOMER_ERP (current) + SAT_CUSTOMER_BUSINESS (current tier). Refreshed as a full snapshot on each dbt run.';
