-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_REGION
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_REGION
(
 STAGE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of this table''s own business key: REGIONKEY',
 REGIONKEY      number(38,0) NOT NULL COMMENT 'ERP region identifier (business key, not enforced as PK here)',
 NAME           varchar(25) COMMENT 'Name of the region',
 COMMENT        varchar(152) COMMENT 'Additional comments about the region',
 SOURCE_SYSTEM  varchar(50) NOT NULL DEFAULT 'ERP' COMMENT 'Source system code',
 LOAD_TIMESTAMP timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_ERP_REGION PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for ERP region reference data. Append-only.';
