-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_NATION_ERP
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_NATION_ERP
(
 NATION_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to HUB_NATION',
 LOAD_DATE       timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF       varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 NAME            varchar(25) COMMENT 'Name of the nation',
 COMMENT         varchar(152) COMMENT 'Additional comments about the nation',
 RECORD_SOURCE   varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_NATION_ERP PRIMARY KEY ( NATION_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_NATION_ERP_HUB_NATION FOREIGN KEY ( NATION_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_NATION ( NATION_HASH_KEY )
)
COMMENT = 'Satellite: descriptive attributes of a nation, from ERP. Region assignment lives in LNK_NATION_REGION, not here. Insert-only.';
