-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_ORDER_LINE
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_ORDER_LINE
(
 LNK_ORDER_LINE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of the ORDERKEY + PARTKEY + SUPPKEY + LINENUMBER combination',
 ORDER_HASH_KEY          varchar(64) NOT NULL COMMENT 'FK to HUB_ORDER',
 PRODUCT_HASH_KEY        varchar(64) NOT NULL COMMENT 'FK to HUB_PRODUCT',
 SUPPLIER_HASH_KEY       varchar(64) NOT NULL COMMENT 'FK to HUB_SUPPLIER',
 LINENUMBER              number(38,0) NOT NULL COMMENT 'Degenerate key element -- distinguishes multiple lines within the same order/product/supplier combination',
 RECORD_SOURCE           varchar(50) NOT NULL COMMENT 'Source system that asserted this relationship',
 LOAD_DATE               timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this relationship was first loaded',

 CONSTRAINT pk_LNK_ORDER_LINE PRIMARY KEY ( LNK_ORDER_LINE_HASH_KEY ),
 CONSTRAINT fk_LNK_ORDER_LINE_HUB_ORDER FOREIGN KEY ( ORDER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_ORDER ( ORDER_HASH_KEY ),
 CONSTRAINT fk_LNK_ORDER_LINE_HUB_PRODUCT FOREIGN KEY ( PRODUCT_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_PRODUCT ( PRODUCT_HASH_KEY ),
 CONSTRAINT fk_LNK_ORDER_LINE_HUB_SUPPLIER FOREIGN KEY ( SUPPLIER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SUPPLIER ( SUPPLIER_HASH_KEY )
)
COMMENT = 'Link: a wholesale order line ties an order to a product and a supplier. Insert-only.';
