-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_CUSTOMER_ERP
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_CUSTOMER_ERP
(
 CUSTOMER_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to HUB_CUSTOMER',
 LOAD_DATE         timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF         varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 NAME              varchar(25) COMMENT 'Name of the customer',
 ADDRESS           varchar(40) COMMENT 'Address of the customer',
 PHONE             varchar(15) COMMENT 'Contact phone number of the customer',
 ACCTBAL           number(12,2) COMMENT 'Account balance of the customer',
 MKTSEGMENT        varchar(10) COMMENT 'Market segment classification of the customer',
 COMMENT           varchar(117) COMMENT 'Additional comments about the customer',
 RECORD_SOURCE     varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_CUSTOMER_ERP PRIMARY KEY ( CUSTOMER_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_CUSTOMER_ERP_HUB_CUSTOMER FOREIGN KEY ( CUSTOMER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_CUSTOMER ( CUSTOMER_HASH_KEY )
)
COMMENT = 'Satellite: descriptive attributes of a wholesale customer, from ERP. Insert-only, new row only when HASH_DIFF changes.';
