-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_REGION_ERP
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_REGION_ERP
(
 REGION_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to HUB_REGION',
 LOAD_DATE       timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF       varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 NAME            varchar(25) COMMENT 'Name of the region',
 COMMENT         varchar(152) COMMENT 'Additional comments about the region',
 RECORD_SOURCE   varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_REGION_ERP PRIMARY KEY ( REGION_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_REGION_ERP_HUB_REGION FOREIGN KEY ( REGION_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_REGION ( REGION_HASH_KEY )
)
COMMENT = 'Satellite: descriptive attributes of a region, from ERP. Insert-only.';
