-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_PRODUCT
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_PRODUCT
(
 PRODUCT_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of PRODUCT_BK. Sourced directly from the contributing source''s Stage STAGE_HASH_KEY.',
 PRODUCT_BK       varchar(30) NOT NULL COMMENT 'Business key exactly as asserted by the contributing source: ERP PARTKEY, EDI VEND_PART_CD, or POS SKU. Identity across sources is NOT resolved here -- see Silver Business same-as-link.',
 RECORD_SOURCE    varchar(50) NOT NULL COMMENT 'Source system that asserted this specific business key',
 LOAD_DATE        timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this business key was first loaded',

 CONSTRAINT pk_HUB_PRODUCT PRIMARY KEY ( PRODUCT_HASH_KEY )
)
COMMENT = 'Hub: product business entity. Multi-source (ERP, EDI, POS), each under its own business key. Insert-only.';
