-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_NATION_REGION
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_NATION_REGION
(
 LNK_NATION_REGION_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of the NATIONKEY + REGIONKEY combination',
 NATION_HASH_KEY            varchar(64) NOT NULL COMMENT 'FK to HUB_NATION',
 REGION_HASH_KEY            varchar(64) NOT NULL COMMENT 'FK to HUB_REGION',
 RECORD_SOURCE              varchar(50) NOT NULL COMMENT 'Source system that asserted this relationship',
 LOAD_DATE                  timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this relationship was first loaded',

 CONSTRAINT pk_LNK_NATION_REGION PRIMARY KEY ( LNK_NATION_REGION_HASH_KEY ),
 CONSTRAINT fk_LNK_NATION_REGION_HUB_NATION FOREIGN KEY ( NATION_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_NATION ( NATION_HASH_KEY ),
 CONSTRAINT fk_LNK_NATION_REGION_HUB_REGION FOREIGN KEY ( REGION_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_REGION ( REGION_HASH_KEY )
)
COMMENT = 'Link: a nation belongs to a region. Insert-only.';
