-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_PART
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_PART
(
 STAGE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of this table''s own business key: PARTKEY',
 PARTKEY        number(38,0) NOT NULL COMMENT 'ERP part master key (business key)',
 NAME           varchar(55) COMMENT 'Name of the part',
 MFGR           varchar(25) COMMENT 'Manufacturer of the part',
 BRAND          varchar(10) COMMENT 'Brand of the part',
 TYPE           varchar(25) COMMENT 'Type or category of the part',
 SIZE           number(38,0) COMMENT 'Size of the part',
 CONTAINER      varchar(10) COMMENT 'Container type used for the part',
 RETAILPRICE    number(12,2) COMMENT 'Retail price of the part',
 COMMENT        varchar(23) COMMENT 'Additional comments about the part',
 SOURCE_SYSTEM  varchar(50) NOT NULL DEFAULT 'ERP' COMMENT 'Source system code',
 LOAD_TIMESTAMP timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_ERP_PART PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for ERP part master data. Append-only.';
