-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SALE
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SALE
(
 SALE_HASH_KEY  varchar(64) NOT NULL COMMENT 'Hash of SALE_TICKET_NO. Sourced directly from POS Stage STAGE_HASH_KEY.',
 SALE_TICKET_NO varchar(30) NOT NULL COMMENT 'Business key: POS sale ticket identifier',
 RECORD_SOURCE  varchar(50) NOT NULL COMMENT 'Source system that first introduced this business key',
 LOAD_DATE      timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this business key was first loaded',

 CONSTRAINT pk_HUB_SALE PRIMARY KEY ( SALE_HASH_KEY )
)
COMMENT = 'Hub: retail sale business entity. Insert-only.';
