-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SUPPLIER
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_SUPPLIER
(
 SUPPLIER_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of SUPPLIER_BK. Sourced directly from the contributing source''s Stage STAGE_HASH_KEY.',
 SUPPLIER_BK       varchar(20) NOT NULL COMMENT 'Business key exactly as asserted by the contributing source: ERP SUPPLIERKEY or EDI VEND_CD. Identity across sources is NOT resolved here -- see Silver Business same-as-link.',
 RECORD_SOURCE     varchar(50) NOT NULL COMMENT 'Source system that asserted this specific business key',
 LOAD_DATE         timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this business key was first loaded',

 CONSTRAINT pk_HUB_SUPPLIER PRIMARY KEY ( SUPPLIER_HASH_KEY )
)
COMMENT = 'Hub: supplier business entity. Multi-source (ERP, EDI), each under its own business key. Insert-only.';
