-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_PARTSUPP_EDI
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_PARTSUPP_EDI
(
 LNK_PARTSUPP_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to LNK_PARTSUPP',
 LOAD_DATE             timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF             varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 AVAIL_QTY_TXT         varchar(20) COMMENT 'Available quantity, landed as text per raw EDI convention -- cast/cleansed in Silver Business',
 LEAD_TM_DAYS          varchar(10) COMMENT 'Lead time in days, landed as text',
 SUPPLY_CST_AMT        varchar(20) COMMENT 'Supply cost, landed as text per raw EDI convention -- cast/cleansed in Silver Business',
 RECORD_SOURCE         varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_PARTSUPP_EDI PRIMARY KEY ( LNK_PARTSUPP_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_PARTSUPP_EDI_LNK_PARTSUPP FOREIGN KEY ( LNK_PARTSUPP_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_PARTSUPP ( LNK_PARTSUPP_HASH_KEY )
)
COMMENT = 'Satellite: descriptive attributes of the product-supplier supply relationship, from the vendor EDI feed. Insert-only, new row only when HASH_DIFF changes (e.g. lead time or cost changes).';
