-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_ORDER_LINE_ERP
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_ORDER_LINE_ERP
(
 LNK_ORDER_LINE_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to LNK_ORDER_LINE',
 LOAD_DATE               timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF               varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 QUANTITY                number(12,2) COMMENT 'Quantity of the item ordered',
 EXTENDEDPRICE           number(12,2) COMMENT 'Extended price of the item',
 DISCOUNT                number(12,4) COMMENT 'Discount rate applied to the item, as a decimal fraction',
 TAX                     number(12,4) COMMENT 'Tax rate applied to the item, as a decimal fraction',
 RETURNFLAG              varchar(1) COMMENT 'Return status of the item',
 LINESTATUS              varchar(1) COMMENT 'Status of the line item',
 SHIPDATE                date COMMENT 'Date the item was shipped',
 COMMITDATE              date COMMENT 'Date the item was committed for shipping',
 RECEIPTDATE             date COMMENT 'Date the item was received',
 SHIPINSTRUCT            varchar(25) COMMENT 'Shipping instructions for the item',
 SHIPMODE                varchar(10) COMMENT 'Shipping mode for the item',
 COMMENT                 varchar(44) COMMENT 'Additional comments about the line item',
 RECORD_SOURCE           varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_ORDER_LINE_ERP PRIMARY KEY ( LNK_ORDER_LINE_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_ORDER_LINE_ERP_LNK_ORDER_LINE FOREIGN KEY ( LNK_ORDER_LINE_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_ORDER_LINE ( LNK_ORDER_LINE_HASH_KEY )
)
COMMENT = 'Satellite: transactional attributes of a wholesale order line, from ERP. Insert-only, new row only when HASH_DIFF changes.';
