-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_SALE_POS
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_SALE_POS
(
 LNK_SALE_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to LNK_SALE',
 LOAD_DATE         timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF         varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 SALE_DATE_TXT     varchar(20) COMMENT 'Sale date, landed as text',
 SALE_STATUS       varchar(20) COMMENT 'POS sale status (e.g. COMPLETED, VOIDED, RETURNED)',
 CASHIER_NAME      varchar(100) COMMENT 'Name of the cashier who processed the sale',
 RECORD_SOURCE     varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_SALE_POS PRIMARY KEY ( LNK_SALE_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_SALE_POS_LNK_SALE FOREIGN KEY ( LNK_SALE_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_SALE ( LNK_SALE_HASH_KEY )
)
COMMENT = 'Satellite: transactional attributes of the sale relationship, from POS. Insert-only, new row only when HASH_DIFF changes (e.g. a sale is later marked VOIDED).';
