-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_STORE
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_STORE
(
 STORE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of STORE_ID. Sourced directly from POS Stage STAGE_HASH_KEY.',
 STORE_ID       varchar(20) NOT NULL COMMENT 'Business key: POS store identifier',
 RECORD_SOURCE  varchar(50) NOT NULL COMMENT 'Source system that first introduced this business key',
 LOAD_DATE      timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this business key was first loaded',

 CONSTRAINT pk_HUB_STORE PRIMARY KEY ( STORE_HASH_KEY )
)
COMMENT = 'Hub: retail store business entity. Insert-only.';
