-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_CUSTOMER
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_CUSTOMER
(
 CUSTOMER_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of CUSTKEY. Sourced directly from ERP Stage STAGE_HASH_KEY.',
 CUSTKEY           number(38,0) NOT NULL COMMENT 'Business key: ERP wholesale customer identifier',
 RECORD_SOURCE     varchar(50) NOT NULL COMMENT 'Source system that first introduced this business key',
 LOAD_DATE         timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this business key was first loaded',

 CONSTRAINT pk_HUB_CUSTOMER PRIMARY KEY ( CUSTOMER_HASH_KEY )
)
COMMENT = 'Hub: wholesale/ERP customer business entity. Insert-only, one row per CUSTKEY ever seen.';
