-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_NATION
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_NATION
(
 NATION_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of NATIONKEY. Sourced directly from ERP Stage STAGE_HASH_KEY.',
 NATIONKEY       number(38,0) NOT NULL COMMENT 'Business key: ERP nation identifier',
 RECORD_SOURCE   varchar(50) NOT NULL COMMENT 'Source system that first introduced this business key',
 LOAD_DATE       timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this business key was first loaded',

 CONSTRAINT pk_HUB_NATION PRIMARY KEY ( NATION_HASH_KEY )
)
COMMENT = 'Hub: nation reference entity. Insert-only.';
