-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_SUPPLIER
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_SUPPLIER
(
 STAGE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of this table''s own business key: SUPPLIERKEY',
 SUPPLIERKEY    number(38,0) NOT NULL COMMENT 'ERP supplier master key (business key)',
 SUPPLIERNAME   varchar(25) COMMENT 'Name of the supplier',
 ADDRESS        varchar(40) COMMENT 'Address of the supplier',
 NATIONKEY      number(38,0) COMMENT 'Referenced nation business key -- virtual relationship only',
 PHONE          varchar(15) COMMENT 'Contact phone number of the supplier',
 ACCOUNTBALANCE number(12,2) COMMENT 'Account balance of the supplier',
 COMMENT        varchar(303) COMMENT 'Additional comments about the supplier',
 SOURCE_SYSTEM  varchar(50) NOT NULL DEFAULT 'ERP' COMMENT 'Source system code',
 LOAD_TIMESTAMP timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_ERP_SUPPLIER PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for ERP supplier master data. Append-only.';
