-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_POS.STG_POS_STORE
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_POS.STG_POS_STORE
(
 STAGE_HASH_KEY   varchar(64) NOT NULL COMMENT 'Hash of this table''s own business key: STORE_ID',
 STORE_ID         varchar(20) NOT NULL COMMENT 'POS store identifier, e.g. STR-004 (business key)',
 STORE_NAME       varchar(100) COMMENT 'Store display name',
 STORE_REGION_TXT varchar(50) COMMENT 'Free-text region name as captured at POS, not conformed to ERP region',
 OPEN_DATE_TXT    varchar(20) COMMENT 'Store open date as captured by the source, landed as text, e.g. 2015-03-01',
 FILE_LOAD_DATE   varchar(20) COMMENT 'Source-asserted file date, landed as text (distinct from LOAD_TIMESTAMP, which is system-generated)',
 SOURCE_SYSTEM    varchar(50) NOT NULL DEFAULT 'POS' COMMENT 'Source system code',
 LOAD_TIMESTAMP   timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_POS_STORE PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for POS store reference data. Append-only.';
