-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_VENDOR_EDI.STG_EDI_PARTSUPP
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_VENDOR_EDI.STG_EDI_PARTSUPP
(
 STAGE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of this table''s own composite business key: VEND_CD + VEND_PART_CD',
 VEND_CD        varchar(20) NOT NULL COMMENT 'Referenced vendor business key -- virtual relationship only (part of this table''s own business key)',
 VEND_PART_CD   varchar(30) NOT NULL COMMENT 'Referenced vendor part business key -- virtual relationship only (part of this table''s own business key)',
 AVAIL_QTY_TXT  varchar(20) COMMENT 'Available quantity, landed as text per raw EDI convention',
 LEAD_TM_DAYS   varchar(10) COMMENT 'Lead time in days, landed as text',
 SUPPLY_CST_AMT varchar(20) COMMENT 'Supply cost, landed as text per raw EDI convention',
 BATCH_ID       varchar(30) COMMENT 'Referenced batch business key -- virtual relationship only',
 SOURCE_SYSTEM  varchar(50) NOT NULL DEFAULT 'VENDOR_EDI' COMMENT 'Source system code',
 LOAD_TIMESTAMP timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_EDI_PARTSUPP PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for vendor part-supply/cost data from the EDI feed. Append-only.';
