-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_ORDER
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_ORDER
(
 LNK_ORDER_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of the ORDERKEY + CUSTKEY combination',
 ORDER_HASH_KEY     varchar(64) NOT NULL COMMENT 'FK to HUB_ORDER',
 CUSTOMER_HASH_KEY  varchar(64) NOT NULL COMMENT 'FK to HUB_CUSTOMER',
 RECORD_SOURCE      varchar(50) NOT NULL COMMENT 'Source system that asserted this relationship',
 LOAD_DATE          timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this relationship was first loaded',

 CONSTRAINT pk_LNK_ORDER PRIMARY KEY ( LNK_ORDER_HASH_KEY ),
 CONSTRAINT fk_LNK_ORDER_HUB_CUSTOMER FOREIGN KEY ( CUSTOMER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_CUSTOMER ( CUSTOMER_HASH_KEY ),
 CONSTRAINT fk_LNK_ORDER_HUB_ORDER FOREIGN KEY ( ORDER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_ORDER ( ORDER_HASH_KEY )
)
COMMENT = 'Link: an order was placed by a customer. Insert-only.';
