-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_LOYALTY_CUSTOMER_POS
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_LOYALTY_CUSTOMER_POS
(
 LOYALTY_CUSTOMER_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to HUB_LOYALTY_CUSTOMER',
 LOAD_DATE                 timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF                 varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 CUST_NAME                 varchar(100) COMMENT 'Customer name as captured at POS',
 CUST_PHONE                varchar(20) COMMENT 'Customer phone as captured at POS',
 SIGNUP_DATE_TXT           varchar(20) COMMENT 'Loyalty signup date, landed as text',
 RECORD_SOURCE             varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_LOYALTY_CUSTOMER_POS PRIMARY KEY ( LOYALTY_CUSTOMER_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_LOYALTY_CUSTOMER_POS_HUB FOREIGN KEY ( LOYALTY_CUSTOMER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_LOYALTY_CUSTOMER ( LOYALTY_CUSTOMER_HASH_KEY )
)
COMMENT = 'Satellite: descriptive attributes of a retail loyalty customer, from POS. Insert-only, new row only when HASH_DIFF changes.';
