-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_SALE_LINE_POS
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_SALE_LINE_POS
(
 LNK_SALE_LINE_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to LNK_SALE_LINE',
 LOAD_DATE              timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF              varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 QTY_SOLD               number(12,2) COMMENT 'Quantity sold on this line',
 UNIT_PRICE             number(12,2) COMMENT 'Unit price at time of sale',
 DISCOUNT_PCT           number(5,2) COMMENT 'Discount percentage applied to the line',
 LINE_TOTAL             number(12,2) COMMENT 'Extended total for the line',
 RECORD_SOURCE          varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_SALE_LINE_POS PRIMARY KEY ( LNK_SALE_LINE_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_SALE_LINE_POS_LNK_SALE_LINE FOREIGN KEY ( LNK_SALE_LINE_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_SALE_LINE ( LNK_SALE_LINE_HASH_KEY )
)
COMMENT = 'Satellite: transactional attributes of a retail sale line, from POS. Insert-only, new row only when HASH_DIFF changes.';
