-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_ORDERS
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_ERP.STG_ERP_ORDERS
(
 STAGE_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of this table''s own business key: ORDERKEY',
 ORDERKEY       number(38,0) NOT NULL COMMENT 'ERP order header key (business key)',
 CUSTKEY        number(38,0) COMMENT 'Referenced customer business key -- virtual relationship only',
 ORDERSTATUS    varchar(1) COMMENT 'Status of the order (O/F/P)',
 TOTALPRICE     number(12,2) COMMENT 'Total price of the order',
 ORDERDATE      date COMMENT 'Date when the order was placed',
 ORDERPRIORITY  varchar(15) COMMENT 'Priority of the order',
 CLERK          varchar(15) COMMENT 'Clerk responsible for the order',
 SHIPPRIORITY   number(38,0) COMMENT 'Shipping priority of the order',
 COMMENT        varchar(79) COMMENT 'Additional comments about the order',
 SOURCE_SYSTEM  varchar(50) NOT NULL DEFAULT 'ERP' COMMENT 'Source system code',
 LOAD_TIMESTAMP timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_ERP_ORDERS PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for ERP wholesale order headers. Append-only.';
