-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_CUSTOMER_NATION
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.LNK_CUSTOMER_NATION
(
 LNK_CUSTOMER_NATION_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of the CUSTKEY + NATIONKEY combination',
 CUSTOMER_HASH_KEY            varchar(64) NOT NULL COMMENT 'FK to HUB_CUSTOMER',
 NATION_HASH_KEY              varchar(64) NOT NULL COMMENT 'FK to HUB_NATION',
 RECORD_SOURCE                varchar(50) NOT NULL COMMENT 'Source system that asserted this relationship',
 LOAD_DATE                    timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this relationship was first loaded',

 CONSTRAINT pk_LNK_CUSTOMER_NATION PRIMARY KEY ( LNK_CUSTOMER_NATION_HASH_KEY ),
 CONSTRAINT fk_LNK_CUSTOMER_NATION_HUB_CUSTOMER FOREIGN KEY ( CUSTOMER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_CUSTOMER ( CUSTOMER_HASH_KEY ),
 CONSTRAINT fk_LNK_CUSTOMER_NATION_HUB_NATION FOREIGN KEY ( NATION_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_NATION ( NATION_HASH_KEY )
)
COMMENT = 'Link: a wholesale customer is based in a nation. Insert-only.';
