-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_PRODUCT_EDI
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.SAT_PRODUCT_EDI
(
 PRODUCT_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to HUB_PRODUCT',
 LOAD_DATE        timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was loaded',
 HASH_DIFF        varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 VEND_PART_DESC   varchar(200) COMMENT 'Vendor''s part description text',
 UNIT_CST_AMT     varchar(20) COMMENT 'Unit cost, landed as text per raw EDI convention -- cast/cleansed in Silver Business',
 PKG_CD           varchar(10) COMMENT 'Vendor packaging code',
 RECORD_SOURCE    varchar(50) NOT NULL COMMENT 'Source system for this descriptive payload',

 CONSTRAINT pk_SAT_PRODUCT_EDI PRIMARY KEY ( PRODUCT_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_PRODUCT_EDI_HUB_PRODUCT FOREIGN KEY ( PRODUCT_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_PRODUCT ( PRODUCT_HASH_KEY )
)
COMMENT = 'Satellite: descriptive attributes of a product, from the vendor EDI feed. Insert-only, new row only when HASH_DIFF changes. Note: POS does not contribute a product satellite -- it only asserts the SKU business key via LNK_SALE_LINE.';
