-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_BUSINESS.SAT_CUSTOMER_BUSINESS
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_BUSINESS.SAT_CUSTOMER_BUSINESS
(
 CUSTOMER_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to HEATHER_SILVER_RAW.HUB_CUSTOMER',
 LOAD_DATE         timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the row was computed',
 HASH_DIFF         varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 CUSTOMER_TIER     varchar(20) COMMENT 'Derived business classification (e.g. HIGH_VALUE, STANDARD, AT_RISK), computed from ACCTBAL and MKTSEGMENT in SAT_CUSTOMER_ERP. Thresholds are a demo placeholder -- adjust to fit whatever business rule you want to show.',
 RECORD_SOURCE     varchar(50) NOT NULL COMMENT 'Not a source system -- this is calculated. Convention: DBT_DERIVED',

 CONSTRAINT pk_SAT_CUSTOMER_BUSINESS PRIMARY KEY ( CUSTOMER_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_CUSTOMER_BUSINESS_HUB_CUSTOMER FOREIGN KEY ( CUSTOMER_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_CUSTOMER ( CUSTOMER_HASH_KEY )
)
COMMENT = 'Satellite: derived customer tier, computed via business rule -- not asserted by any source. Insert-only, new row only when HASH_DIFF changes (i.e. the customer''s tier actually changes).';
