-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_REGION
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_RAW.HUB_REGION
(
 REGION_HASH_KEY varchar(64) NOT NULL COMMENT 'Hash of REGIONKEY. Sourced directly from ERP Stage STAGE_HASH_KEY.',
 REGIONKEY       number(38,0) NOT NULL COMMENT 'Business key: ERP region identifier',
 RECORD_SOURCE   varchar(50) NOT NULL COMMENT 'Source system that first introduced this business key',
 LOAD_DATE       timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this business key was first loaded',

 CONSTRAINT pk_HUB_REGION PRIMARY KEY ( REGION_HASH_KEY )
)
COMMENT = 'Hub: region reference entity. Insert-only.';
