-- ******************************* SqlDBM: Snowflake *******************************
-- * Generated by SqlDBM: Dev - Silver Build Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_SILVER_BUSINESS.SAT_SAL_PRODUCT_MATCH
CREATE TABLE "SQLDBM_DEMO".HEATHER_SILVER_BUSINESS.SAT_SAL_PRODUCT_MATCH
(
 SAL_PRODUCT_HASH_KEY varchar(64) NOT NULL COMMENT 'FK to SAL_PRODUCT',
 LOAD_DATE            timestamp_ltz(9) NOT NULL COMMENT 'Timestamp this version of the match rationale was recorded',
 HASH_DIFF            varchar(64) NOT NULL COMMENT 'Hash of all descriptive columns below -- drives insert-only change detection',
 MATCH_METHOD         varchar(50) COMMENT 'How the match was determined, e.g. EXACT_DESCRIPTION_MATCH, MANUAL_CROSSREF, FUZZY_NAME_MATCH. Demo placeholder -- adjust to whatever matching logic you want to show.',
 MATCH_CONFIDENCE     number(5,2) COMMENT 'Confidence score for the match, 0-100. Demo placeholder.',
 RECORD_SOURCE        varchar(50) NOT NULL COMMENT 'Not a source system -- this is derived. Convention: DBT_DERIVED',

 CONSTRAINT pk_SAT_SAL_PRODUCT_MATCH PRIMARY KEY ( SAL_PRODUCT_HASH_KEY, LOAD_DATE ),
 CONSTRAINT fk_SAT_SAL_PRODUCT_MATCH_SAL_PRODUCT FOREIGN KEY ( SAL_PRODUCT_HASH_KEY ) REFERENCES "SQLDBM_DEMO".HEATHER_SILVER_BUSINESS.SAL_PRODUCT ( SAL_PRODUCT_HASH_KEY )
)
COMMENT = 'Satellite: rationale for a product same-as match -- not asserted by any source, computed by dbt matching logic. Insert-only.';
