-- **************************** SqlDBM: Snowflake ***************************
-- * Generated by SqlDBM: DEV - Stage Sprint 01 by heather.ready@sqldbm.com *

-- ************************************** "SQLDBM_DEMO".HEATHER_STG_POS.STG_POS_CUSTOMER
CREATE OR REPLACE TRANSIENT TABLE "SQLDBM_DEMO".HEATHER_STG_POS.STG_POS_CUSTOMER
(
 STAGE_HASH_KEY  varchar(64) NOT NULL COMMENT 'Hash of this table''s own business key: LOYALTY_ID',
 LOYALTY_ID      varchar(20) NOT NULL COMMENT 'POS loyalty program identifier (business key) -- different flavor than ERP CUSTKEY',
 CUST_NAME       varchar(100) COMMENT 'Customer name as captured at POS',
 CUST_PHONE      varchar(20) COMMENT 'Customer phone as captured at POS',
 HOME_STORE_ID   varchar(20) COMMENT 'Referenced store business key -- virtual relationship only',
 SIGNUP_DATE_TXT varchar(20) COMMENT 'Loyalty signup date landed as text',
 FILE_LOAD_DATE  varchar(20) COMMENT 'Source-asserted file date, landed as text',
 SOURCE_SYSTEM   varchar(50) NOT NULL DEFAULT 'POS' COMMENT 'Source system code',
 LOAD_TIMESTAMP  timestamp_ltz(9) NOT NULL COMMENT 'System-generated timestamp of this load run',

 CONSTRAINT pk_STG_POS_CUSTOMER PRIMARY KEY ( STAGE_HASH_KEY, LOAD_TIMESTAMP )
)
COMMENT = 'Staging table for POS loyalty customer data (retail). Append-only.';
